export const NICHE_QUESTIONS: Record<string, string[]> = {
  // ── Tình yêu ──────────────────────────────────────────
  love: [
    "Bức tranh tổng thể tình cảm của tôi lúc này là gì?",
    "Năng lượng tình yêu đang bao quanh tôi như thế nào?",
    "Tôi cần thay đổi điều gì để thu hút tình yêu lành mạnh?",
    "Bài học tình cảm lớn nhất tôi cần học lúc này là gì?",
    "Điều gì đang cản trở tôi mở lòng với tình yêu?",
    "Tình yêu sẽ mang đến điều gì cho tôi trong giai đoạn tới?",
    "Tôi đang tìm kiếm điều gì trong một mối tình?",
    "Khuôn mẫu cảm xúc nào tôi cứ lặp đi lặp lại mà không hay biết?",
    "Tôi có đang yêu đúng người, đúng thời điểm không?",
    "Điều gì khiến tôi trở nên hấp dẫn hơn trong mắt người khác?",
    "Ranh giới nào tôi cần thiết lập để tình yêu được lành mạnh?",
  ],
  ex: [
    "Người yêu cũ từng dành cho tôi tình cảm như thế nào?",
    "Hiện tại người yêu cũ còn giữ tình cảm gì với tôi không?",
    "Người yêu cũ nghĩ gì về việc quay lại?",
    "Bản chất và ý nghĩa của mối quan hệ cũ là gì?",
    "Nếu quay lại, mối quan hệ sẽ tiến triển ra sao?",
    "Lời khuyên để tôi đối diện với người yêu cũ?",
    "Người yêu cũ có hối hận về những gì đã xảy ra không?",
    "Tôi có đang giữ kỳ vọng không thực tế với người cũ không?",
    "Vũ trụ nhắn gửi điều gì về mối quan hệ đã qua này?",
    "Bài học nào tôi cần rút ra từ mối tình cũ để không vấp ngã lại?",
  ],
  current_love: [
    "Người yêu hiện tại dành cho tôi tình cảm thế nào?",
    "Người ấy kỳ vọng gì ở mối quan hệ này?",
    "Người ấy đang suy nghĩ thế nào về tình yêu của chúng tôi?",
    "Thử thách hoặc trở ngại trong mối quan hệ hiện tại là gì?",
    "Lời khuyên để mối quan hệ của chúng tôi bền vững hơn?",
    "Tương lai của mối quan hệ này sẽ đi về đâu?",
    "Người ấy có thực sự sẵn sàng cho một mối quan hệ nghiêm túc không?",
    "Điều gì đang được nói ngầm mà chưa ai dám đặt lên bàn?",
    "Mối quan hệ này đang ở giai đoạn nào trong hành trình của nó?",
    "Tôi có đang đưa ra quyết định dựa trên tình yêu hay nỗi sợ mất mát?",
    "Hành động nào của tôi có thể làm mối quan hệ tốt lên ngay lúc này?",
  ],
  ambiguous: [
    "Người này thật sự có cảm xúc gì với tôi?",
    "Họ mong đợi điều gì từ mối quan hệ này?",
    "Trong suy nghĩ của họ, tôi có vị trí thế nào?",
    "Nếu tiến xa hơn, kết quả có tốt đẹp không?",
    "Lời khuyên để tôi ứng xử trong mối quan hệ mập mờ này?",
    "Tôi có nên chủ động làm rõ mối quan hệ không?",
    "Điều gì khiến họ chưa sẵn sàng bước tới?",
    "Tôi có đang tự đặt kỳ vọng quá cao vào người này không?",
    "Năng lượng thật sự của người này dành cho tôi là gì?",
    "Tôi cần nhìn thấy điều gì rõ ràng hơn trong tình huống này?",
  ],
  crush: [
    "Crush của tôi là người có tính cách như thế nào?",
    "Người tôi thích có đang để ý đến tôi không?",
    "Giữa tôi và crush có khả năng phát triển tình cảm không?",
    "Lời khuyên để tôi tiến gần hơn đến crush?",
    "Ai đang thầm yêu tôi mà tôi chưa biết?",
    "Tôi có nên tỏ tình hay tiếp tục chờ đợi?",
    "Cảm xúc của crush dành cho tôi có chân thật không?",
    "Điều gì cản tôi tiến lại gần người tôi thích?",
    "Mối quan hệ này có tương lai nếu tôi chủ động không?",
    "Tôi cần trở thành phiên bản tốt hơn thế nào để phù hợp với người này?",
  ],
  future_love: [
    "Tôi có thể gặp người mình thích trong khoảng thời gian nào?",
    "Người yêu tương lai của tôi có đặc điểm ra sao?",
    "Người yêu tương lai sẽ đối xử với tôi như thế nào?",
    "Tổng quan tình yêu giữa tôi và người yêu tương lai thế nào?",
    "Người chồng/vợ tương lai của tôi có thể làm nghề gì?",
    "Tôi cần chuẩn bị gì để sẵn sàng đón nhận tình yêu mới?",
    "Tôi sẽ gặp người ấy trong hoàn cảnh như thế nào?",
    "Tình yêu trong tương lai sẽ khác gì so với những mối tình đã qua?",
    "Điều gì tôi cần buông bỏ để tình yêu mới có thể đến?",
    "Năng lượng nào đang kéo người phù hợp lại gần tôi hơn?",
  ],
  someone: [
    "Người ấy có sợ mất tôi không?",
    "Người ấy có nghĩ đến việc quay lại không?",
    "Người ấy có nhớ tôi không?",
    "Tôi và người ấy có thể đi đến kết thúc hạnh phúc không?",
    "Người ấy đang giấu tôi điều gì?",
    "Người ấy thật sự cảm thấy gì về tôi lúc này?",
    "Điều gì đang ngăn người ấy tiến lại gần tôi hơn?",
    "Người ấy nhìn nhận tôi như thế nào so với những người khác?",
    "Thông điệp nào người ấy muốn truyền đạt nhưng không nói ra?",
    "Tôi có nên tiếp tục chờ đợi người này không?",
    "Năng lượng của mối liên kết giữa chúng tôi đang ở đâu?",
  ],
  marriage: [
    "Nguyên nhân nào khiến cuộc hôn nhân của tôi gặp khó khăn?",
    "Điều gì đang ảnh hưởng mạnh đến mối quan hệ vợ chồng của tôi?",
    "Có thể cứu vãn hôn nhân của tôi bằng cách nào?",
    "Nửa kia của tôi mong muốn điều gì ở tôi?",
    "Hôn nhân của tôi sẽ đi đến đâu nếu tiếp tục như hiện tại?",
    "Tôi có nên tiếp tục hay buông tay mối hôn nhân này?",
    "Điều gì chưa được nói thẳng giữa hai vợ chồng chúng tôi?",
    "Tôi cần thay đổi điều gì trong cách đối xử với nửa kia?",
    "Liệu có yếu tố bên ngoài nào đang phá hoại hôn nhân không?",
    "Nền tảng sâu nhất gắn kết hai chúng tôi lại với nhau là gì?",
    "Bước đầu tiên để hôn nhân của chúng tôi trở về trạng thái tốt đẹp?",
  ],
  conflict: [
    "Tôi có nên là người chủ động hòa giải trước không?",
    "Nếu nhìn từ góc nhìn của người kia, tôi sẽ thấy điều gì?",
    "Tôi có nên tha thứ cho người gây xung đột với mình không?",
    "Kết quả sau cùng của xung đột gần đây sẽ ra sao?",
    "Điều gì thực sự gây ra mâu thuẫn này?",
    "Mâu thuẫn này đang dạy cho tôi bài học gì về bản thân?",
    "Tôi có đang phản ứng thái quá hay cảm xúc của tôi có lý do chính đáng?",
    "Ranh giới nào tôi cần thiết lập sau khi giải quyết xong xung đột này?",
    "Thời điểm nào thích hợp để tôi tiếp cận người kia?",
    "Năng lượng của mối quan hệ sau khi xung đột được giải quyết sẽ thế nào?",
  ],
  breakup: [
    "Tôi có nên cố gắng hàn gắn sau khi chia tay không?",
    "Lý do ẩn khuất nào khiến chúng tôi chia tay?",
    "Người kia có hối hận và muốn quay lại không?",
    "Nếu tôi tha thứ, mối quan hệ sẽ đi về đâu?",
    "Tôi cần chữa lành điều gì trong bản thân sau cuộc chia tay này?",
    "Tôi nên đối mặt với người kia hay giữ khoảng cách?",
    "Bước đầu tiên để tôi tiến về phía trước là gì?",
    "Điều tốt đẹp nào tôi có thể mang theo từ mối quan hệ đã qua?",
    "Tôi đã học được gì về bản thân qua mối tình này?",
    "Khi nào tôi sẽ sẵn sàng mở lòng với một mối tình mới?",
  ],
  long_distance: [
    "Mối tình xa cách của tôi có bền vững không?",
    "Người yêu xa có thực sự chung thủy với tôi không?",
    "Chúng tôi có cơ hội thu hẹp khoảng cách địa lý không?",
    "Thách thức lớn nhất trong mối tình xa này là gì?",
    "Tôi có nên tiếp tục chờ đợi hay nên buông tay?",
    "Điều gì đang giữ chúng tôi gắn kết dù cách xa nhau?",
    "Khi nào chúng tôi có thể ở bên nhau trong cùng một nơi?",
    "Sự tin tưởng giữa hai chúng tôi có đang vững chắc không?",
    "Tôi cần làm gì để duy trì tình yêu dù khoảng cách?",
    "Mối tình này có thực sự đủ mạnh để vượt qua tất cả không?",
  ],
  jealousy: [
    "Người yêu có đang che giấu mối quan hệ nào với tôi không?",
    "Liệu có người thứ ba nào đang cố tình xâm phạm mối quan hệ của tôi?",
    "Người ấy có yêu tôi thật lòng không?",
    "Cảm giác ghen tuông của tôi có căn cứ không?",
    "Tôi nên xử lý tình huống này như thế nào?",
    "Nỗi bất an của tôi xuất phát từ đâu — từ thực tế hay từ quá khứ?",
    "Tôi cần làm gì để xây dựng lại niềm tin trong mối quan hệ?",
    "Điều gì tôi cần nói thẳng với người ấy để cảm thấy an tâm hơn?",
    "Người ấy nhìn nhận sự ghen tuông của tôi như thế nào?",
    "Ranh giới lành mạnh nào cần được thiết lập trong mối quan hệ này?",
  ],
  self_love: [
    "Tôi đang đối xử với bản thân như thế nào?",
    "Vết thương nội tâm nào tôi cần chữa lành đầu tiên?",
    "Điều gì đang cản tôi yêu chính mình?",
    "Tôi có đang đặt ra giới hạn rõ ràng trong các mối quan hệ không?",
    "Tôi cần buông bỏ điều gì để sống tại thời điểm hiện tại?",
    "Tôi đang nói chuyện với chính mình như thế nào — có đang tự phán xét không?",
    "Điều gì khiến tôi cảm thấy xứng đáng được yêu thương?",
    "Tôi cần chăm sóc bản thân như thế nào hơn nữa?",
    "Hành động nhỏ nào hôm nay có thể thể hiện tình yêu thương với chính mình?",
    "Tôi đang bỏ qua nhu cầu cảm xúc nào của chính mình?",
  ],
  finding_love: [
    "Tôi cần thay đổi điều gì để thu hút tình yêu đích thực?",
    "Tại sao tình yêu chưa đến với tôi dù tôi đã sẵn sàng?",
    "Người phù hợp với tôi đang ở đâu trong cuộc sống này?",
    "Tôi có đang vô tình đẩy cơ duyên ra xa không?",
    "Điều gì cần xảy ra trước khi tôi gặp được người đúng?",
    "Năng lượng tình yêu của tôi đang phát ra tín hiệu gì cho vũ trụ?",
    "Khuôn mẫu nào tôi cần phá vỡ để tình yêu có thể đến?",
    "Tôi đang sợ điều gì trong tình yêu mà chưa dám thừa nhận?",
    "Đâu là nơi tôi có thể gặp được người phù hợp?",
    "Bài học từ quá khứ nào cần được học xong trước khi tiếp tục?",
  ],
  compatibility: [
    "Chúng tôi có thực sự hợp nhau để đi lâu dài không?",
    "Điểm khác biệt lớn nhất giữa hai người là gì?",
    "Hai người cần thay đổi điều gì để hiểu nhau hơn?",
    "Năng lượng tổng thể của mối quan hệ này đang ở trạng thái nào?",
    "Điều gì gắn kết và điều gì đang kéo chúng tôi xa nhau?",
    "Giá trị sống của hai chúng tôi có đi cùng một hướng không?",
    "Cách giao tiếp của chúng tôi có đang gây hiểu lầm không?",
    "Điểm mạnh của mối quan hệ này là gì cần được trân trọng?",
    "Chúng tôi hỗ trợ lẫn nhau phát triển như thế nào?",
    "Chúng tôi có đang kỳ vọng những điều khác nhau từ mối quan hệ không?",
  ],
  toxic_relationship: [
    "Tại sao tôi cứ mãi lặp lại khuôn mẫu bế tắc này trong tình yêu?",
    "Có nên dứt khoát chấm dứt mối quan hệ mang lại nhiều nước mắt này?",
    "Cách nào để tự giải thoát bản thân khỏi sự kìm kẹp tình cảm?",
    "Người kia có đang thao túng tâm lý tôi không?",
    "Bài học lớn nhất sau sự tan vỡ này là gì?",
    "Điều gì khiến tôi cứ ở lại dù biết mối quan hệ này không lành mạnh?",
    "Tôi đánh mất phần nào của bản thân trong mối quan hệ này?",
    "Bước đầu tiên để tôi thoát ra khỏi vòng lặp này là gì?",
    "Tôi cần được hỗ trợ như thế nào trong giai đoạn này?",
    "Điều gì đang giữ tôi ở lại — tình yêu thật hay nỗi sợ hãi?",
  ],
  soulmate: [
    "Dấu hiệu nhận biết soulmate của tôi sắp xuất hiện là gì?",
    "Liệu người tôi vừa gặp có phải là mảnh ghép định mệnh?",
    "Điểm chung nào gắn kết linh hồn hai người trong vạn dặm đời?",
    "Sự hội ngộ này mang lại điều gì cho sự phát triển của cả hai?",
    "Làm cách nào để vun đắp trọn vẹn sự kết nối kỳ diệu này?",
    "Tôi có đang ở quá gần soulmate của mình mà không nhận ra không?",
    "Mối liên kết tiền kiếp giữa tôi và người này là gì?",
    "Soulmate của tôi đang ở đâu trong cuộc hành trình này?",
    "Điều gì tôi cần làm để sẵn sàng đón nhận soulmate?",
    "Năng lượng của mối liên kết linh hồn này đang nói gì?",
  ],
  reconciliation: [
    "Nếu quay lại, cả hai đã đủ trưởng thành để không vấp ngã?",
    "Tôi cần thay đổi điểm nào nếu muốn gương vỡ lại lành?",
    "Đối phương đã sẵn sàng bỏ qua cái tôi chưa?",
    "Cơ hội tái hợp lần này có mang lại hạnh phúc thật sự?",
    "Vũ trụ khuyên tôi nên buông xuôi hay cố níu giữ?",
    "Lý do gốc rễ của sự đổ vỡ có được giải quyết triệt để chưa?",
    "Điều gì sẽ khác biệt nếu chúng tôi quay lại lần này?",
    "Tôi có đang tái hợp vì tình yêu thật hay vì nỗi cô đơn?",
    "Thời điểm nào phù hợp để tiếp cận và mở cuộc nói chuyện?",
    "Kết quả tốt nhất và xấu nhất nếu tái hợp là gì?",
  ],
  secret_admirer: [
    "Ai đang âm thầm quan tâm tôi từ xa?",
    "Cảm xúc thực sự của họ dành cho tôi sâu đậm đến đâu?",
    "Tôi có nên bật đèn xanh cho họ bước tới không?",
    "Lời tỏ tình có sắp sửa diễn ra trong thời gian tới?",
    "Người ngưỡng mộ tôi thầm lặng này là người như thế nào?",
    "Tại sao họ chưa chủ động tiến lại gần tôi hơn?",
    "Nếu mối quan hệ này phát triển, nó sẽ đi về đâu?",
    "Có nhiều hơn một người đang để ý đến tôi không?",
    "Tôi cần làm gì để người ấy dũng cảm bày tỏ tình cảm?",
    "Năng lượng của sự kết nối tiềm ẩn này là gì?",
  ],
  friendship: [
    "Mối quan hệ bạn bè của chúng tôi hiện tại ra sao?",
    "Người bạn này có thực sự chân thành với tôi không?",
    "Làm sao để chúng tôi gắn kết và hiểu nhau hơn?",
    "Có xích mích nào đang ngầm tồn tại giữa chúng tôi không?",
    "Tương lai của tình bạn này sẽ đi về đâu?",
    "Ai trong số những người quen là bạn thật sự của tôi?",
    "Tôi có đang cho đi quá nhiều trong tình bạn mà không nhận lại không?",
    "Điều gì khiến tình bạn này trở nên đặc biệt?",
    "Tôi nên tiếp tục vun đắp tình bạn này hay nên giữ khoảng cách?",
    "Điều gì sẽ xảy ra nếu tôi thành thật với người bạn này?",
  ],
  pregnancy: [
    "Kế hoạch sinh con của tôi sắp tới có thuận lợi không?",
    "Giai đoạn thai kỳ của tôi cần lưu ý điều gì về năng lượng?",
    "Mối liên kết tâm linh giữa tôi và đứa trẻ sắp chào đời?",
    "Làm sao để tôi chuẩn bị tốt nhất vai trò làm cha/mẹ?",
    "Thông điệp vũ trụ dành cho kế hoạch gia đình của tôi?",
    "Điều tôi cần buông bỏ để sẵn sàng đón nhận sự sống mới?",
    "Nỗi lo lắng lớn nhất của tôi về việc làm cha/mẹ là gì và có cơ sở không?",
    "Năng lượng nào tôi cần nuôi dưỡng trong giai đoạn này?",
    "Tôi cần hỗ trợ thêm từ ai trong hành trình này?",
    "Điều kỳ diệu nào đang chờ đợi gia đình tôi phía trước?",
  ],
  gossip: [
    "Ai là người đang gieo rắc tin đồn về tôi?",
    "Tại sao thị phi này lại xuất hiện trong cuộc đời tôi?",
    "Cách tốt nhất để tôi dập tắt ngọn lửa đàm tiếu này là gì?",
    "Thị phi này có ảnh hưởng thực tế đến công việc của tôi không?",
    "Bài học tôi nhận được sau biến cố danh tiếng này là gì?",
    "Tôi có nên đối mặt trực tiếp hay im lặng để sự việc tự lắng xuống?",
    "Ai đang đứng về phía tôi trong tình huống này?",
    "Động cơ thật sự của người tung tin đồn là gì?",
    "Danh tiếng của tôi sẽ phục hồi như thế nào?",
    "Điều gì tôi có thể học từ trải nghiệm đau đớn này?",
  ],
  family: [
    "Thời gian tới gia đình tôi có gặp khó khăn gì không?",
    "Các mối quan hệ trong gia đình tôi sẽ diễn biến ra sao?",
    "Tôi nên làm gì để cải thiện mối quan hệ với gia đình?",
    "Lời khuyên chung cho gia đình tôi trong thời gian tới?",
    "Thành viên gia đình nào đang cần tôi quan tâm nhiều hơn?",
    "Có điều gì chưa được nói thẳng trong gia đình tôi không?",
    "Tôi có đang mang theo vết thương từ gia đình gốc vào cuộc sống hiện tại không?",
    "Năng lượng chung của gia đình tôi đang như thế nào?",
    "Làm sao để tôi thiết lập ranh giới lành mạnh với gia đình?",
    "Điều gì sẽ giúp gia đình tôi gắn kết và yêu thương nhau hơn?",
  ],
  // ── Sự nghiệp ─────────────────────────────────────────
  career: [
    "Tình hình công việc hiện tại của tôi có tốt không?",
    "Công việc trong 3 tháng tới của tôi sẽ như thế nào?",
    "Tôi có nên chuyển chỗ làm không?",
    "Môi trường làm việc mới có đặc điểm thế nào?",
    "Năng lực nào của tôi đang chưa được khai thác đúng chỗ?",
    "Điều gì đang cản trở sự nghiệp của tôi tiến lên?",
    "Đồng nghiệp trong môi trường làm việc mới sẽ ra sao?",
    "Nhiệm vụ hôm nay cấp trên giao có rủi ro gì không?",
    "Kết quả dự án tôi đang làm sẽ được đánh giá ra sao?",
    "Tôi có phù hợp với văn hóa của công ty hiện tại không?",
    "Thái độ làm việc dạo này của tôi có bị chê trách không?",
    "Làm sao để tìm thấy lại niềm vui khi đi làm?",
  ],
  job_search: [
    "Trong 3 tháng tới tôi có tìm được công việc phù hợp không?",
    "Những khó khăn tôi sẽ gặp khi đi xin việc là gì?",
    "Điểm mạnh của tôi trong lần ứng tuyển này?",
    "Điểm yếu của tôi trong lần ứng tuyển này?",
    "Lĩnh vực nào phù hợp nhất với tôi để ứng tuyển?",
    "Tôi nên tìm việc theo hướng nào để nhanh thành công nhất?",
    "Nhà tuyển dụng ấn tượng với điều gì nhất ở tôi?",
    "Tôi cần cải thiện kỹ năng nào để tăng cơ hội được nhận?",
    "Cơ hội việc làm tốt nào đang chờ tôi mà tôi chưa biết?",
    "Thời điểm nào trong năm tôi nên chủ động tìm kiếm cơ hội mới?",
  ],
  promotion: [
    "Tôi có cơ hội thăng chức trong thời gian tới không?",
    "Điều gì đang giữ tôi lại khỏi vị trí cao hơn?",
    "Tôi nên làm gì để nổi bật hơn trong mắt quản lý?",
    "Cấp trên hiện tại nhìn tôi như thế nào?",
    "Lộ trình sự nghiệp tốt nhất cho tôi lúc này là gì?",
    "Năm nay tôi có cơ hội được tăng bậc chức danh không?",
    "Đâu là kỹ năng tôi còn yếu nhất trong công việc?",
    "Sếp có nhìn nhận đúng năng lực thực sự của tôi không?",
    "Tôi cần thể hiện điều gì thêm để được giao trọng trách lớn hơn?",
    "Có ai đang ngầm cạnh tranh vị trí với tôi không?",
  ],
  business: [
    "Dự án kinh doanh của tôi có tiềm năng không?",
    "Thách thức lớn nhất trong kế hoạch kinh doanh của tôi là gì?",
    "Tôi nên tập trung vào lĩnh vực nào để kiếm tiền hiệu quả?",
    "Đối tác kinh doanh hiện tại có phù hợp với tôi không?",
    "Năng lượng nào tôi cần mang vào việc kinh doanh?",
    "Thời điểm nào là tốt để ra mắt sản phẩm / dịch vụ?",
    "Khách hàng mục tiêu của tôi đang cần điều gì nhất?",
    "Điều gì cần thay đổi trong chiến lược kinh doanh hiện tại?",
    "Tôi nên mở rộng hay củng cố những gì đang có trước?",
    "Rủi ro lớn nhất trong kế hoạch kinh doanh sắp tới là gì?",
    "Đâu là cơ hội thị trường tôi đang bỏ lỡ?",
  ],
  colleague: [
    "Đồng nghiệp đang đối xử với tôi ra sao?",
    "Có ai trong công ty đang muốn hại tôi không?",
    "Tôi có nên tin tưởng đồng nghiệp/sếp hiện tại không?",
    "Cách đồng nghiệp đánh giá tôi là gì?",
    "Tôi nên ứng xử như thế nào với môi trường làm việc phức tạp này?",
    "Đồng nghiệp trong môi trường làm việc mới sẽ ra sao?",
    "Ai là người tôi có thể tin tưởng tuyệt đối nơi làm việc?",
    "Mối quan hệ với đồng nghiệp X hiện tại đang ở trạng thái nào?",
    "Tôi cần cải thiện cách giao tiếp với đồng nghiệp như thế nào?",
    "Có đồng minh quan trọng nào tôi chưa nhận ra ở chỗ làm không?",
  ],
  career_change: [
    "Tôi có nên từ bỏ công việc hiện tại không?",
    "Hướng đi nào phù hợp với năng lực và đam mê của tôi?",
    "Việc chuyển sang ngành mới có mang lại hạnh phúc không?",
    "Rủi ro lớn nhất nếu tôi đổi hướng nghề nghiệp là gì?",
    "Lời khuyên cho tôi khi chuẩn bị bước ra khỏi vùng an toàn?",
    "Tôi có đủ nền tảng để chuyển nghề thành công không?",
    "Ngành mới tôi đang nhắm tới có phù hợp với tính cách tôi không?",
    "Điều tôi sợ nhất khi đổi nghề có xảy ra không?",
    "Thời điểm nào thích hợp nhất để bắt đầu bước chuyển này?",
    "Tôi cần học thêm kỹ năng nào trước khi chuyển ngành?",
  ],
  freelance: [
    "Làm freelance có phù hợp với tôi thời điểm này không?",
    "Tôi có thể kiếm sống ổn định bằng công việc tự do không?",
    "Lĩnh vực nào có thể mang lại thu nhập tốt cho tôi khi làm tự do?",
    "Điểm yếu nào của tôi cần cải thiện khi làm việc độc lập?",
    "Khách hàng đầu tiên của tôi trong hành trình freelance sẽ đến từ đâu?",
    "Tôi có đang định giá dịch vụ của mình đúng với giá trị thực không?",
    "Làm sao để tôi xây dựng thương hiệu cá nhân vững chắc?",
    "Thách thức tâm lý lớn nhất khi làm tự do là gì và cách vượt qua?",
    "Tôi có nên kiếm ổn định từ freelance trước khi nghỉ việc chính không?",
    "Mạng lưới kết nối nào sẽ giúp sự nghiệp tự do của tôi phát triển?",
  ],
  interview: [
    "Buổi phỏng vấn sắp tới của tôi có thành công không?",
    "Diện mạo và cách trình bày nào giúp tôi gây ấn tượng?",
    "Điểm yếu nào có thể làm tôi mất điểm trong mắt nhà tuyển dụng?",
    "Môi trường làm việc mới này có phù hợp với tôi không?",
    "Lời khuyên trước buổi phỏng vấn quan trọng này?",
    "Câu hỏi nào của nhà tuyển dụng tôi cần chuẩn bị kỹ nhất?",
    "Điều gì khiến tôi nổi bật hơn so với các ứng viên khác?",
    "Công ty này có thực sự phù hợp với định hướng dài hạn của tôi không?",
    "Tôi có nên thương lượng mức lương trong buổi phỏng vấn này không?",
    "Sau phỏng vấn, tôi có thể mong đợi điều gì xảy ra tiếp theo?",
  ],
  legal: [
    "Vấn đề pháp lý hiện tại của tôi có kết quả khả quan không?",
    "Tôi cần chuẩn bị giấy tờ hoặc đối sách gì để xoay chuyển?",
    "Người hỗ trợ pháp lý hoặc luật sư của tôi có đáng tin cậy không?",
    "Vấn đề kiện tụng này kéo dài bao lâu nữa?",
    "Vũ trụ khuyên tôi nên nhượng bộ hay chiến đấu đến cùng?",
    "Bên đối lập đang có những lợi thế gì tôi chưa biết?",
    "Điều gì có thể đảo ngược tình thế theo hướng có lợi cho tôi?",
    "Chi phí và hao tổn thực sự nếu vụ việc kéo dài là gì?",
    "Có giải pháp nào ngoài tòa án để giải quyết vụ việc này không?",
    "Bài học nào từ vụ việc này giúp tôi không tái phạm?",
  ],
  moving: [
    "Việc chuyển nhà / xuất ngoại lúc này có mang lại tài lộc không?",
    "Năng lượng tại nơi ở mới có phù hợp với tôi không?",
    "Rào cản lớn nhất cản bước tôi định cư tại vùng đất mới là gì?",
    "Quá trình di dời có thuận lợi hay gặp trắc trở?",
    "Cuộc sống của tôi sẽ thay đổi thế nào sau khi chuyển chỗ?",
    "Tôi sẽ hòa nhập với cộng đồng mới như thế nào?",
    "Có điều gì tôi đang bỏ lại phía sau mà sẽ hối tiếc không?",
    "Cơ hội nào đang chờ tôi ở vùng đất mới?",
    "Thời điểm nào trong năm thích hợp nhất để thực hiện việc chuyển này?",
    "Tôi cần chuẩn bị tâm lý gì trước khi rời đi?",
  ],
  burnout: [
    "Tôi phải làm gì để khôi phục lại cảm hứng công việc?",
    "Khoảng thời gian kiệt sức này bao giờ mới chấm dứt?",
    "Tôi có đang ép bản thân chạy theo những tiêu chuẩn sai lầm?",
    "Bình yên thực sự đang chực chờ tôi ở phương hướng nào?",
    "Điều gì cần buông bỏ để lấy lại năng lượng?",
    "Dấu hiệu nào cho thấy tôi cần phải dừng lại và nghỉ ngơi ngay?",
    "Nguyên nhân sâu xa nào khiến tôi rơi vào tình trạng kiệt sức này?",
    "Ai hoặc điều gì đang hút cạn năng lượng của tôi?",
    "Tôi cần tạo ra khoảng trống như thế nào trong cuộc sống?",
    "Sau giai đoạn phục hồi, sự nghiệp của tôi sẽ đi theo hướng nào?",
  ],
  startup: [
    "Ý tưởng khởi nghiệp của tôi có được thị trường đón nhận?",
    "Người đồng sáng lập này có đáng để tôi giao phó sứ mệnh không?",
    "Nên gọi vốn lúc này hay tự thân gầy dựng?",
    "Thử thách khó lường nhất trong giai đoạn đầu startup là gì?",
    "Sản phẩm/dịch vụ của tôi có thực sự giải quyết vấn đề người dùng không?",
    "Đâu là rủi ro mà tôi đang xem nhẹ nhưng thực ra rất quan trọng?",
    "Nhà đầu tư phù hợp nhất cho startup của tôi là ai?",
    "Khi nào tôi nên pivot nếu hướng đi hiện tại không hiệu quả?",
    "Điều gì sẽ giúp startup của tôi tạo ra sự khác biệt bền vững?",
    "Tôi cần xây dựng đội ngũ như thế nào để vượt qua giai đoạn đầu?",
  ],
  workplace_politics: [
    "Kẻ nào đang ném đá giấu tay trong bộ phận của tôi?",
    "Sáng suốt nhất bây giờ là cắn răng chịu đựng hay vùng lên?",
    "Sếp có thực sự hiểu và ghi nhận nỗ lực của tôi không?",
    "Bao giờ những lời đơm đặt này mới tan biến đi?",
    "Ai đang ngầm cướp công lao của tôi?",
    "Công việc hiện tại có đang bào mòn tuổi trẻ của tôi không?",
    "Tôi nên liên minh với ai để bảo vệ vị trí của mình?",
    "Có nên báo cáo sự việc lên cấp trên hay tự xử lý?",
    "Môi trường độc hại này có ảnh hưởng đến sức khỏe tâm thần của tôi không?",
    "Điều gì sẽ xảy ra nếu tôi tiếp tục im lặng về vấn đề này?",
  ],
  side_hustle: [
    "Ý tưởng kiếm thêm tiền này có mang lại lợi nhuận thực tế?",
    "Tôi nên phân bổ thời gian thế nào để không ảnh hưởng việc chính?",
    "Ai có thể là cộng sự tốt nhất cho tôi ở nghề tay trái?",
    "Nghề phụ này liệu có khả năng trở thành sự nghiệp trọn đời?",
    "Thị trường mục tiêu nào phù hợp nhất với sản phẩm/dịch vụ của tôi?",
    "Tôi có đang dàn trải quá mỏng giữa công việc chính và nghề tay trái không?",
    "Chiến lược marketing nào hiệu quả nhất cho nghề phụ của tôi?",
    "Khi nào nghề phụ này có thể bắt đầu tạo ra thu nhập ổn định?",
    "Điều gì tôi cần học thêm để nghề tay trái phát triển nhanh hơn?",
    "Rủi ro pháp lý hoặc tài chính nào tôi cần lưu ý?",
  ],
  // ── Tài chính ─────────────────────────────────────────
  finance: [
    "Cơ hội tài chính nào đang đến với tôi?",
    "Tình hình tài chính của tôi trong 3 tháng tới thế nào?",
    "Mục tiêu tài chính hiện tại có khả năng đạt được không?",
    "Trở ngại tài chính lớn nhất của tôi hiện tại là gì?",
    "Làm sao để chi tiêu hợp lý hơn?",
    "Tôi có đang có những mối lo lắng về tài chính không cần thiết không?",
    "Điều gì đang cản tôi đạt được sự tự do tài chính?",
    "Nguồn thu nhập nào có thể giúp tôi cải thiện tình hình hiện tại?",
    "Thói quen tài chính nào tôi cần thay đổi ngay?",
    "Tài chính của tôi trong năm tới sẽ đi theo hướng nào?",
  ],
  investment: [
    "Kênh đầu tư nào phù hợp với tôi nhất hiện tại?",
    "Dự án/cổ phiếu tôi đang cân nhắc có nên đầu tư không?",
    "Rủi ro nào tôi cần cảnh giác khi đầu tư?",
    "Thời điểm nào là tốt để tôi bước vào thị trường?",
    "Điểm mạnh của tôi với tư cách nhà đầu tư là gì?",
    "Tôi có đang bị cảm xúc chi phối quyết định đầu tư không?",
    "Danh mục đầu tư hiện tại có đang cân bằng và an toàn không?",
    "Cổ phiếu/tài sản nào tôi nên cắt lỗ và thoát khỏi ngay?",
    "Chiến lược dài hạn nào phù hợp nhất với mục tiêu tài chính của tôi?",
    "Có người nào đang cho tôi lời khuyên đầu tư không đáng tin không?",
  ],
  debt: [
    "Tôi có thể thoát khỏi tình trạng nợ nần trong thời gian này không?",
    "Năng lượng nào đang cản tôi thoát khỏi nợ?",
    "Tôi nên ưu tiên trả khoản nợ nào trước?",
    "Bài học tài chính tôi cần học từ tình huống này là gì?",
    "Điều gì dẫn tôi đến tình trạng nợ nần này?",
    "Người nào có thể hỗ trợ tôi vượt qua giai đoạn này?",
    "Kế hoạch trả nợ nào thực tế và bền vững nhất với tôi?",
    "Tôi có đang vay mượn vì lý do đúng đắn không?",
    "Gánh nặng tài chính này ảnh hưởng đến sức khỏe tinh thần của tôi như thế nào?",
    "Bao giờ tôi có thể hoàn toàn thoát khỏi áp lực nợ?",
  ],
  savings: [
    "Tôi có đạt được mục tiêu tiết kiệm trong năm nay không?",
    "Tôi nên thay đổi thói quen chi tiêu như thế nào?",
    "Nguồn thu nhập mới nào có thể xuất hiện với tôi?",
    "Tôi đang lãng phí năng lượng và tiền bạc vào đâu?",
    "Con số tiết kiệm thực tế tôi có thể đạt trong vòng 1 năm là bao nhiêu?",
    "Điều gì khiến tôi tiêu tiền nhiều hơn mức cần thiết?",
    "Tôi có đang tiết kiệm vì đúng mục tiêu hay chỉ vì sợ hãi?",
    "Chiến lược tiết kiệm nào phù hợp nhất với lối sống hiện tại?",
    "Tôi cần xây dựng quỹ khẩn cấp như thế nào?",
    "Điều gì giúp tôi duy trì kỷ luật tài chính lâu dài?",
  ],
  luck_money: [
    "Tài lộc của tôi trong tháng này thế nào?",
    "May mắn nào sắp đến với tôi?",
    "Điều gì đang cản trở luồng tiền chảy vào cuộc đời tôi?",
    "Hướng nào giúp tôi tài lộc tốt nhất?",
    "Thời điểm nào trong năm tôi nên nắm bắt cơ hội tài chính?",
    "Tôi có đang tự giới hạn sự thịnh vượng của mình không?",
    "Điềm lành nào đang báo hiệu sự thay đổi tài chính cho tôi?",
    "Năng lượng của tôi với tiền bạc đang ở trạng thái nào?",
    "Cách nào để tôi khai thông dòng chảy tài chính bị nghẽn?",
    "Điều gì vũ trụ muốn tôi hiểu về mối quan hệ của mình với tiền bạc?",
  ],
  real_estate: [
    "Thời điểm này có nên mua bất động sản không?",
    "Giao dịch nhà đất tôi đang cân nhắc có thuận lợi không?",
    "Rủi ro lớn nhất trong phi vụ bất động sản này là gì?",
    "Tôi có nên bán tài sản hiện tại vào lúc này không?",
    "Năng lượng của ngôi nhà / mảnh đất này có phù hợp với tôi?",
    "Đối tác trong giao dịch bất động sản này có đáng tin cậy không?",
    "Tôi có đang bị thổi phồng giá và mua nhầm không?",
    "Khu vực nào sẽ có tiềm năng tăng giá tốt trong tương lai?",
    "Tôi nên thuê hay mua trong giai đoạn này?",
    "Bước tiếp theo nào tôi cần làm để giao dịch thành công?",
  ],
  financial_loss: [
    "Nguyên nhân sâu xa của tình trạng thua lỗ hiện tại là gì?",
    "Tôi có thể phục hồi tài chính trong thời gian sắp tới không?",
    "Bài học quan trọng nhất từ giai đoạn khó khăn này là gì?",
    "Điều gì cần thay đổi để tôi thoát khỏi vòng lặp thất bại tài chính?",
    "Hướng nào có thể giúp tôi khởi động lại dòng tiền?",
    "Ai hoặc điều gì đã đóng góp vào tình trạng thua lỗ này?",
    "Tôi có đang tự trách mình quá mức cho tình huống này không?",
    "Nguồn lực ẩn nào tôi chưa khai thác để vực dậy tài chính?",
    "Tôi cần hỗ trợ tài chính hay tinh thần nhiều hơn lúc này?",
    "Khi nào tình hình tài chính của tôi sẽ bắt đầu ổn định trở lại?",
  ],
  sudden_wealth: [
    "Cơ hội tài chính bất ngờ nào đang hướng về phía tôi?",
    "Tôi có nên nắm bắt cơ hội tiền bạc này ngay không?",
    "Năng lượng xung quanh khoản tiền bất ngờ này là gì?",
    "Làm sao để tôi giữ được nguồn tiền may mắn lâu dài?",
    "Điều kiện nào cần xảy ra để vận may tài chính này thành hiện thực?",
    "Tôi có đang chuẩn bị tâm lý tốt để đón nhận sự thịnh vượng không?",
    "Cạm bẫy nào tôi cần tránh khi có tiền nhiều đột ngột?",
    "Tôi nên phân bổ khoản tiền này như thế nào để tối ưu?",
    "Ai xung quanh tôi sẽ thay đổi khi họ biết tôi có điều kiện hơn?",
    "Khoản tiền này có thực sự mang lại hạnh phúc hay chỉ là tạm thời?",
  ],
  // ── Sức khỏe ──────────────────────────────────────────
  health: [
    "Tình hình sức khỏe sắp tới của tôi thế nào?",
    "Điều gì đang là trở ngại đối với sức khỏe của tôi?",
    "Tôi nên thay đổi lối sống hiện tại ra sao?",
    "Tôi đang bỏ qua vấn đề gì liên quan đến sức khỏe?",
    "Tôi nên làm gì để tăng cường năng lượng và thể chất?",
    "Dấu hiệu cơ thể nào tôi cần chú ý hơn trong thời gian này?",
    "Thói quen sinh hoạt nào đang ảnh hưởng tiêu cực đến sức khỏe?",
    "Tôi cần bổ sung điều gì vào cuộc sống để cảm thấy khỏe mạnh hơn?",
    "Mối liên hệ giữa trạng thái cảm xúc và sức khỏe thể chất của tôi là gì?",
    "Tôi có đang chăm sóc bản thân đúng cách chưa?",
  ],
  mental: [
    "Cảm xúc nào đang ảnh hưởng tiêu cực đến cuộc sống của tôi?",
    "Tôi có đang ở trong trạng thái kiệt sức (burnout) không?",
    "Vết thương tâm lý nào tôi chưa đối mặt?",
    "Tôi cần làm gì để bảo vệ sức khỏe tâm thần?",
    "Lo âu hay sợ hãi nào đang khiến tôi không tiến về phía trước?",
    "Nguồn hạnh phúc đích thực của tôi là gì?",
    "Tôi có đang kiểm soát cảm xúc lành mạnh hay đang dồn nén không?",
    "Điều gì giúp tôi cảm thấy bình tĩnh và an toàn nhất?",
    "Tôi đang thiếu điều gì để cảm thấy hài lòng với cuộc sống?",
    "Liệu pháp hoặc hành động nào giúp tôi cải thiện sức khỏe tinh thần ngay bây giờ?",
    "Người nào trong cuộc đời tôi ảnh hưởng tốt đến trạng thái tinh thần?",
  ],
  energy: [
    "Chakra nào của tôi đang mất cân bằng?",
    "Năng lượng nào tôi cần tẩy rửa và giải phóng?",
    "Tôi có đang chịu ảnh hưởng của năng lượng tiêu cực từ người khác không?",
    "Phương pháp thực hành nào giúp tôi cân bằng cơ thể và tâm trí?",
    "Tôi nên hướng năng lượng của mình vào đâu thời điểm này?",
    "Trạng thái năng lượng tổng thể của tôi hiện tại ra sao?",
    "Điều gì đang hút cạn sức sống của tôi mỗi ngày?",
    "Thực hành tâm linh hoặc thiền định nào phù hợp nhất với tôi?",
    "Làm sao để tôi tái nạp năng lượng sau những giai đoạn kiệt sức?",
    "Có người hoặc môi trường nào đang làm ô nhiễm trường năng lượng của tôi không?",
  ],
  diet: [
    "Lối sống của tôi hiện tại có ảnh hưởng xấu đến sức khỏe không?",
    "Tôi nên thay đổi thói quen nào để cải thiện sức khỏe?",
    "Điều nào cổ vũ tôi để duy trì thói quen lành mạnh hơn?",
    "Tôi đang bỏ qua yếu tố nào nhưng quan trọng với sức khỏe?",
    "Chế độ ăn uống hiện tại có đang phù hợp với nhu cầu cơ thể không?",
    "Rào cản nào khiến tôi khó duy trì thói quen ăn uống lành mạnh?",
    "Mối liên hệ giữa cảm xúc và thói quen ăn uống của tôi là gì?",
    "Tôi có đang dùng thức ăn để đối phó với cảm xúc không?",
    "Thực phẩm hoặc thói quen nào tôi nên thêm vào cuộc sống ngay?",
    "Điều gì giúp tôi kiên trì với kế hoạch sức khỏe dù bận rộn?",
  ],
  pet: [
    "Thú cưng của tôi đang cảm thấy thế nào?",
    "Thú cưng có mang lại năng lượng chữa lành cho ngôi nhà không?",
    "Vấn đề sức khỏe hiện tại của bé cưng có đáng lo ngại không?",
    "Mối liên hệ tiền kiếp giữa tôi và thú cưng là gì?",
    "Làm sao để tôi chăm sóc và kết nối tốt hơn với chúng?",
    "Thú cưng của tôi đang cố giao tiếp điều gì với tôi?",
    "Điều tôi cần thay đổi trong cách chăm sóc thú cưng là gì?",
    "Thú cưng có đang phản chiếu trạng thái năng lượng của tôi không?",
    "Thú cưng sẽ ổn như thế nào nếu tôi phải đi vắng dài ngày?",
    "Liên kết giữa tôi và thú cưng sẽ thay đổi như thế nào theo thời gian?",
  ],
  healing: [
    "Tôi đang ở giai đoạn nào trong hành trình chữa lành?",
    "Vết thương nào cần được chú ý nhiều nhất lúc này?",
    "Điều gì đang cản tôi chữa lành hoàn toàn?",
    "Phương pháp chữa lành nào phù hợp nhất với tôi?",
    "Khi nào tôi có thể cảm thấy toàn vẹn và bình an trở lại?",
    "Tôi có đang cố gắng chữa lành quá nhanh thay vì cho phép mình được cảm thấy không?",
    "Bài học sâu sắc nhất mà giai đoạn đau khổ này đang dạy tôi là gì?",
    "Ai hoặc điều gì có thể là người đồng hành trong hành trình này?",
    "Cơ thể tôi đang giữ đau ở đâu và cần được giải phóng như thế nào?",
    "Phiên bản khỏe mạnh nhất của tôi trông như thế nào?",
  ],
  stress: [
    "Nguồn gốc sâu xa của căng thẳng tôi đang chịu đựng là gì?",
    "Tôi có đang lo lắng về điều không trong tầm kiểm soát không?",
    "Cách nào giúp tôi giải tỏa áp lực hiệu quả nhất lúc này?",
    "Điều gì cần buông bỏ để tâm trí nhẹ nhàng hơn?",
    "Bao giờ giai đoạn căng thẳng này mới qua đi?",
    "Tôi có đang phản ứng với căng thẳng theo cách lành mạnh không?",
    "Ai đang đổ thêm áp lực vào cuộc đời tôi mà tôi nên đặt ranh giới?",
    "Điều gì thực sự cần thiết và điều gì chỉ là trách nhiệm tự áp đặt?",
    "Cơ thể tôi đang yêu cầu gì mà tôi chưa đáp ứng?",
    "Khoảng không gian yên bình nào giúp tôi phục hồi tốt nhất?",
  ],
  trauma: [
    "Vết thương cũ nào đang ảnh hưởng đến hiện tại của tôi?",
    "Tôi cần làm gì để đối mặt với chấn thương này lành mạnh hơn?",
    "Ai hoặc điều gì có thể hỗ trợ tôi trong quá trình chữa lành?",
    "Tôi có đang vô tình tái tạo những mô thức đau khổ từ quá khứ không?",
    "Bước đầu tiên để tôi giải phóng bản thân khỏi tổn thương là gì?",
    "Điều gì tôi cần tha thứ — cho bản thân hoặc cho người khác?",
    "Tôi có đang giữ chặt chấn thương như một phần danh tính của mình không?",
    "Câu chuyện nào tôi đang tự kể về bản thân cần được viết lại?",
    "Liệu pháp hoặc cách tiếp cận nào phù hợp nhất với hành trình hồi phục của tôi?",
    "Khi nào tôi sẽ cảm thấy đủ an toàn để tin tưởng lại?",
  ],
  // ── Bản thân ──────────────────────────────────────────
  study: [
    "Tổng quan việc học tập của tôi hiện tại ra sao?",
    "Kết quả học tập của tôi trong 3 tháng tới thế nào?",
    "Tôi có đạt kết quả tốt trong kỳ thi sắp tới không?",
    "Lời khuyên quan trọng về học tập thời gian tới?",
    "Tôi cần thay đổi phương pháp học như thế nào?",
    "Ngành học / chuyên môn nào phù hợp nhất với tôi?",
    "Điều gì đang cản trở tập trung và hiệu quả học tập của tôi?",
    "Tôi có đang học đúng ngành mình thực sự muốn không?",
    "Mối quan hệ với thầy cô/bạn bè trong học tập có ảnh hưởng như thế nào?",
    "Kiến thức hay kỹ năng nào quan trọng nhất tôi cần bổ sung ngay?",
  ],
  study_abroad: [
    "Tôi có thực sự phù hợp để đi du học không?",
    "Cuộc sống của tôi khi đi du học sẽ như thế nào?",
    "Những khó khăn nào có thể xảy ra khi đi du học?",
    "Lời khuyên dành cho tôi khi chuẩn bị du học?",
    "Đất nước nào phù hợp nhất với tôi để du học?",
    "Visa và thủ tục du học của tôi sẽ thuận lợi không?",
    "Tôi sẽ hòa nhập với môi trường văn hóa mới như thế nào?",
    "Cơ hội việc làm sau khi du học của tôi có tốt không?",
    "Tôi có nên đi du học một mình hay cùng với người quen không?",
    "Học bổng hoặc hỗ trợ tài chính có sẵn sàng cho tôi không?",
  ],
  self: [
    "Tôi hiện tại là người như thế nào?",
    "Hình ảnh của tôi trong mắt người khác ra sao?",
    "Tôi cần chú ý gì để phát triển bản thân tốt hơn?",
    "Xu hướng của tôi trong tình yêu và các mối quan hệ là gì?",
    "Tôi đang tự giới hạn bản thân ở điểm nào?",
    "Điều gì làm tôi khác biệt và đặc biệt so với người khác?",
    "Phiên bản tốt nhất của tôi trông như thế nào?",
    "Tôi cần buông bỏ niềm tin nào để tiến về phía trước?",
    "Điều gì thực sự quan trọng với tôi ở giai đoạn này?",
    "Tôi đang dùng bao nhiêu tiềm năng thực sự của mình?",
  ],
  purpose: [
    "Sứ mệnh của tôi trong cuộc đời này là gì?",
    "Tôi sinh ra để làm điều gì?",
    "Tôi đang lãng phí tiềm năng của mình ở đâu?",
    "Giá trị cốt lõi nào tôi cần sống đúng hơn?",
    "Hành động nào đưa tôi lại gần hơn với đích đến thực sự?",
    "Điều gì tôi sẽ hối tiếc nếu không thử trong cuộc đời này?",
    "Cuộc sống có ý nghĩa đối với tôi trông như thế nào?",
    "Tôi đang đi trên con đường đúng hay đã lạc hướng?",
    "Điều gì khiến tôi cảm thấy sống có mục đích nhất?",
    "Vũ trụ đang hướng tôi tới đâu trong giai đoạn này?",
  ],
  shadow_self: [
    "Điều gì trong bản thân tôi mà tôi đang cố tình tránh đối diện?",
    "Bóng tối nào đang âm thầm chi phối hành động của tôi?",
    "Tôi đang tự phá hoại bản thân theo những cách nào?",
    "Khó khăn hiện tại đang dạy tôi điều gì về chính mình?",
    "Tôi cần hòa giải điều gì bên trong để bước tiếp?",
    "Nỗi sợ sâu nhất của tôi là gì và nó đang kiểm soát tôi như thế nào?",
    "Tôi đang mang mặt nạ gì với người khác mà không dám tháo ra?",
    "Phần bóng tối nào của tôi có thể trở thành sức mạnh nếu được tích hợp?",
    "Tôi đang xét xử bản thân về điều gì mà không thực sự xứng đáng?",
    "Điều gì tôi cần tha thứ cho chính mình để được tự do?",
  ],
  decision: [
    "Tôi nên chọn hướng nào trong quyết định lần này?",
    "Đâu là điều tôi thực sự muốn khi phải lựa chọn?",
    "Nếu cứ trì hoãn, điều gì sẽ xảy ra?",
    "Lời khuyên tương lai cho tôi liên quan đến quyết định này?",
    "Tôi đang sợ điều gì khiến khó ra quyết định?",
    "Tôi đang ra quyết định dựa trên lý trí hay cảm xúc?",
    "Kết quả tốt nhất và xấu nhất của từng lựa chọn là gì?",
    "Ai có thể cho tôi lời khuyên khách quan nhất trong tình huống này?",
    "Điều gì sẽ xảy ra 5 năm sau nếu tôi chọn hướng này?",
    "Trực giác của tôi đang chỉ về phía nào?",
  ],
  travel: [
    "Chuyến đi này có thuận lợi và mang lại điều tốt không?",
    "Tôi có nên dời đến nơi ở mới không?",
    "Điều gì tôi cần chuẩn bị cho chuyến đi?",
    "Nơi nào mang lại cơ hội tốt cho tôi?",
    "Có rủi ro nào trong chuyến đi mà tôi cần lưu ý không?",
    "Chuyến đi này sẽ thay đổi tôi như thế nào?",
    "Tôi sẽ gặp ai hoặc trải nghiệm điều gì đáng nhớ trong chuyến đi?",
    "Thời điểm nào trong năm thích hợp nhất để tôi du lịch?",
    "Tôi có nên đi một mình hay cùng với người khác không?",
    "Chuyến đi có giúp tôi tìm lại chính mình không?",
  ],
  spiritual: [
    "Tôi đang ở giai đoạn nào trong hành trình tâm linh của mình?",
    "Năng lượng bảo hộ nào đang ở bên cạnh tôi?",
    "Tôi có tiền duyên với con đường tâm linh nào không?",
    "Điều gì vũ trụ muốn nhắn gửi cho tôi lúc này?",
    "Tôi có năng khiếu tâm linh hay thấu cảm nào chưa khám phá?",
    "Thực hành tâm linh nào sẽ mang lại sự tăng trưởng lớn nhất cho tôi?",
    "Tôi có đang tiến hóa đúng theo mục đích linh hồn không?",
    "Dấu hiệu nào cho thấy tôi đang đi đúng hướng tâm linh?",
    "Điều gì đang cản trở tôi mở rộng ý thức và nhận thức?",
    "Người hướng dẫn tâm linh hoặc thầy nào phù hợp với tôi?",
  ],
  dream: [
    "Giấc mơ lặp đi lặp lại gần đây của tôi chứa thông điệp gì?",
    "Hình ảnh đáng sợ trong mơ cảnh báo tôi điều gì từ tiềm thức?",
    "Có điềm báo tương lai nào ẩn giấu trong giấc mộng đêm qua không?",
    "Vũ trụ muốn nhắc nhở tôi giải quyết vấn đề gì qua giấc mơ?",
    "Tôi nên hành động thế nào ở đời thực sau khi thấy điềm báo?",
    "Nhân vật trong giấc mơ tượng trưng cho điều gì trong cuộc sống?",
    "Tiềm thức đang cố nói với tôi điều gì mà ý thức chưa chịu nghe?",
    "Giấc mơ tốt lành gần đây nhất có ý nghĩa gì?",
    "Làm sao để tôi khai thác thông điệp từ giấc mơ hiệu quả hơn?",
    "Có liên hệ nào giữa giấc mơ và tình trạng tinh thần hiện tại không?",
  ],
  past_life: [
    "Tôi mang theo món nợ tiền kiếp nào ảnh hưởng đến hiện tại?",
    "Mối liên hệ giữa tôi và người ấy trong tiền kiếp là gì?",
    "Năng khiếu bẩm sinh hiện tại của tôi đến từ tiền kiếp nào?",
    "Chấp niệm nào từ tiền kiếp vẫn còn đang cản bước tôi?",
    "Tôi cần làm gì để giải thoát những nỗi đau từ quá khứ?",
    "Tiền kiếp của tôi sống ở nơi nào và làm gì?",
    "Bài học linh hồn nào tôi đã thực hành qua nhiều kiếp?",
    "Điểm mạnh nào từ tiền kiếp tôi có thể khai thác trong đời này?",
    "Có hợp đồng linh hồn nào với người quan trọng trong cuộc đời tôi không?",
    "Điều gì chứng tỏ tiền kiếp đang ảnh hưởng đến hành vi của tôi hiện tại?",
  ],
  karma: [
    "Khó khăn tôi đang chịu đựng có phải xuất phát từ nghiệp quả?",
    "Bài học nhân quả lớn nhất mà tôi cần tốt nghiệp là gì?",
    "Làm sao để tôi gieo những hạt giống thiện lành cho tương lai?",
    "Có chướng nghiệp nào với gia đình dòng họ đang trói buộc tôi?",
    "Tôi đã trả xong món nghiệp đối với người này hay chưa?",
    "Hành động nào ngay hôm nay có thể tạo nghiệp lành cho tương lai?",
    "Tôi có đang cố tình bỏ qua bài học mà vũ trụ đang cố dạy không?",
    "Điều gì tôi đã làm trong quá khứ đang trở lại với tôi lúc này?",
    "Chuỗi nhân quả nào đang lặp lại trong cuộc đời tôi cần được cắt đứt?",
    "Người nào trong cuộc sống này là thầy nghiệp chướng của tôi?",
  ],
  lost_item: [
    "Món đồ quý giá tôi làm rơi hiện đang nằm ở phương hướng nào?",
    "Trạng thái hiện tại của món đồ còn nguyên hay đã mất mát?",
    "Tôi nên tìm đồ vật này ở nơi ánh sáng hay trong góc khuất?",
    "Sự thất lạc này có mang ý nghĩa cảnh báo tôi bất cẩn điều gì?",
    "Tỷ lệ tôi tìm lại được đồ vật này là bao nhiêu phần trăm?",
    "Ai có thể biết thông tin về món đồ bị mất của tôi?",
    "Tôi nên tìm kiếm ở khu vực nào trước tiên?",
    "Thời điểm nào trong ngày thích hợp để đi tìm lại đồ vật?",
    "Điều gì tôi cần chú ý hơn để tránh mất đồ lần sau?",
    "Nếu không tìm được, vũ trụ muốn tôi buông bỏ điều gì qua sự kiện này?",
  ],
  exams: [
    "Kết quả kỳ thi sắp tới của tôi sẽ như thế nào?",
    "Tôi cần tập trung ôn luyện điều gì nhất?",
    "Trạng thái tinh thần của tôi trước kỳ thi có ổn định không?",
    "Có yếu tố bất ngờ nào ảnh hưởng đến kết quả thi không?",
    "Lời khuyên của vũ trụ cho tôi trước kỳ thi quan trọng này?",
    "Tôi có đang ôn tập theo đúng hướng không?",
    "Môn học nào cần được đầu tư thêm thời gian nhất?",
    "Làm sao để tôi kiểm soát lo lắng và căng thẳng trước thi?",
    "Kết quả kỳ thi này sẽ ảnh hưởng đến con đường học vấn của tôi như thế nào?",
    "Tôi cần ngủ và nghỉ ngơi ra sao để não bộ hoạt động tốt nhất?",
  ],
  scholarship: [
    "Cơ hội nhận học bổng của tôi lần này có cao không?",
    "Điều gì đang cản tôi đạt được học bổng mình muốn?",
    "Tôi nên tập trung vào điểm mạnh nào trong hồ sơ xin học bổng?",
    "Có cơ hội học bổng phù hợp nào tôi chưa biết đến không?",
    "Học bổng này có thực sự là con đường đúng cho tôi không?",
    "Bài luận hoặc đề xuất nào của tôi sẽ gây ấn tượng nhất?",
    "Điều gì khiến hồ sơ của tôi nổi bật hơn so với ứng viên khác?",
    "Tôi có nên ứng tuyển nhiều học bổng cùng lúc không?",
    "Phỏng vấn học bổng sắp tới có diễn ra suôn sẻ không?",
    "Nếu không đạt được lần này, cơ hội tiếp theo của tôi là gì?",
  ],
  talent: [
    "Tài năng ẩn nào tôi chưa khai thác hết tiềm năng?",
    "Đam mê nào của tôi có thể trở thành nguồn sống?",
    "Tôi đang tự giới hạn bản thân ở điểm nào với tài năng của mình?",
    "Con đường nào giúp tôi phát huy tốt nhất năng khiếu trời phú?",
    "Điều gì cần xảy ra để đam mê của tôi được thế giới nhìn nhận?",
    "Tôi có đang so sánh tài năng của mình với người khác một cách không lành mạnh không?",
    "Điều gì khiến tôi nghi ngờ khả năng của chính mình?",
    "Lĩnh vực sáng tạo nào tôi nên khám phá thêm?",
    "Ai hoặc điều gì có thể giúp tài năng của tôi tỏa sáng hơn?",
    "Đam mê nào từ thời thơ ấu tôi bỏ quên mà nên nhặt lên lại?",
  ],
  spirit_guide: [
    "Năng lượng bảo hộ nào đang hiện diện bên cạnh tôi?",
    "Thông điệp nào thần hộ mệnh đang cố gửi đến tôi?",
    "Tôi có đang lắng nghe tiếng thì thầm của trực giác không?",
    "Làm sao để tôi kết nối sâu hơn với năng lượng bảo hộ của mình?",
    "Điều gì vũ trụ muốn tôi biết về hành trình phía trước?",
    "Thần hộ mệnh của tôi đang xuất hiện qua dấu hiệu nào trong cuộc sống?",
    "Tôi có đang cưỡng lại sự hướng dẫn từ trực giác và linh cảm không?",
    "Ai trong số người thân đã khuất đang bảo vệ tôi từ phía bên kia?",
    "Nghi lễ hoặc thực hành nào giúp tôi mở kênh kết nối tâm linh?",
    "Thông điệp số hoặc dấu hiệu nào đang xuất hiện nhiều với tôi gần đây?",
  ],
  general: [
    "Thông điệp chung của vũ trụ cho tôi là gì?",
    "Tôi cần tập trung điều gì thời gian này?",
    "Năng lượng nào đang bao quanh tôi?",
    "Thử thách lớn nhất tôi sẽ đối mặt là gì?",
    "Điều tốt đẹp nào sắp đến với tôi?",
    "Bài học lớn nhất trong giai đoạn này của cuộc đời tôi là gì?",
    "Điều gì tôi cần buông bỏ để tiến về phía trước?",
    "Cơ hội nào đang đến mà tôi chưa nhận ra?",
    "Người nào hoặc điều gì đang thực sự hỗ trợ tôi lúc này?",
    "Vũ trụ muốn tôi học được điều gì từ tình huống hiện tại?",
    "Hành động nhỏ nào ngay hôm nay có thể thay đổi hướng đi của tôi?",
  ],
};
